
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;

public class Principal3 extends javax.swing.JFrame {

    /**
     * Creates new form Principal3
     */
    private String name = null;

    public Principal3(String user) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.name = user;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        red = new javax.swing.JButton();
        magenta = new javax.swing.JButton();
        green = new javax.swing.JButton();
        blue = new javax.swing.JButton();
        cyan = new javax.swing.JButton();
        volver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel.setBackground(new java.awt.Color(0, 0, 51));

        red.setBackground(new java.awt.Color(255, 0, 0));
        red.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redActionPerformed(evt);
            }
        });

        magenta.setBackground(new java.awt.Color(255, 51, 255));
        magenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                magentaActionPerformed(evt);
            }
        });

        green.setBackground(new java.awt.Color(0, 255, 51));
        green.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                greenActionPerformed(evt);
            }
        });

        blue.setBackground(new java.awt.Color(0, 0, 255));
        blue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blueActionPerformed(evt);
            }
        });

        cyan.setBackground(new java.awt.Color(0, 255, 255));
        cyan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cyanActionPerformed(evt);
            }
        });

        volver.setBackground(new java.awt.Color(0, 0, 102));
        volver.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        volver.setText("Volver ←");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(red, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(green, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(157, 157, 157)
                        .addComponent(magenta, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(blue, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81)
                        .addComponent(cyan, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(volver)))
                .addContainerGap(383, Short.MAX_VALUE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(red)
                .addGap(49, 49, 49)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(green)
                    .addComponent(magenta))
                .addContainerGap(196, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(volver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cyan)
                    .addComponent(blue))
                .addGap(97, 97, 97))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void redActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redActionPerformed
        // BLACKJACK
        Mesa1 a = new Mesa1(name);
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_redActionPerformed

    private void magentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_magentaActionPerformed
        // CARRERAS
        Pista a = new Pista(name);
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_magentaActionPerformed

    private void greenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_greenActionPerformed
        // ROMPECABEZAS
        mant a = new mant(name);
        a.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_greenActionPerformed

    private void blueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blueActionPerformed
        // SOPA DE LETRAS
        inicio a = new inicio(name);
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_blueActionPerformed

    private void cyanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cyanActionPerformed
       // SERPIENTES Y ESCALERAS
        mant a = new mant(name);
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cyanActionPerformed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed

        Principal2 a = new Principal2();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_volverActionPerformed
    @Override
    public void paint(Graphics g) {
        super.paint(g);
        Graphics gr = panel.getGraphics();

        gr.setColor(Color.yellow);
        int[] vx = {60, 123, 150, 177, 240, 190, 200, 150, 100, 110};
        int[] vy = {160, 160, 100, 160, 160, 200, 260, 220, 260, 200};
        gr.fillPolygon(vx, vy, 10);

        gr.setColor(Color.red);
        int[] xt1 = {150, 123, 177};
        int[] yt1 = {100, 160, 160};
        gr.fillPolygon(xt1, yt1, 3);
        gr.fillOval(320, 180, 10, 10);

        gr.setColor(Color.green);
        int[] xt2 = {123, 60, 110};
        int[] yt2 = {160, 160, 200};
        gr.fillPolygon(xt2, yt2, 3);
        gr.fillOval(320, 260, 10, 10);

        gr.setColor(Color.magenta);
        int[] xt3 = {177, 240, 190};
        int[] yt3 = {160, 160, 200};
        gr.fillPolygon(xt3, yt3, 3);
        gr.fillOval(320, 200, 10, 10);

        gr.setColor(Color.blue);
        int[] xt4 = {110, 150, 100};
        int[] yt4 = {200, 220, 260};
        gr.fillPolygon(xt4, yt4, 3);
        gr.fillOval(320, 240, 10, 10);

        gr.setColor(Color.cyan);
        int[] xt5 = {190, 150, 200};
        int[] yt5 = {200, 220, 260};
        gr.fillPolygon(xt5, yt5, 3);
        gr.fillOval(320, 220, 10, 10);

        gr.setColor(Color.orange);
        Font f3 = new Font("Engravers MT", Font.BOLD, 25);
        gr.setFont(f3);
        gr.drawString("STAR Games" + "", 310, 100);

        g.fillOval(141, 200, 8, 13);
        g.fillOval(167, 200, 8, 13);

        gr.setColor(Color.white);
        gr.fillOval(136, 170, 3, 3);
        gr.fillOval(162, 170, 3, 3);

        gr.setColor(Color.black);
        g.fillOval(141, 217, 35, 20);
        gr.setColor(Color.yellow);
        gr.fillRect(133, 185, 35, 9);

        gr.setColor(Color.white);
        Font f2 = new Font("Monospaced", Font.PLAIN, 15);
        gr.setFont(f2);
        gr.drawString("En STAR GAMES puedes disfrutar", 280, 140);
        gr.drawString("de 5 juegos distintos:", 280, 160);

        gr.drawString("  ROJO: Cartas", 320, 190);
        gr.drawString("  MAGENTA: Carreras", 320, 210);
        gr.drawString("  CYAN: Serpientes y escaleras", 320, 230);
        gr.drawString("  AZUL: Sopa de letras", 320, 250);
        gr.drawString("  VERDE: Rompecabezas", 320, 270);

        gr.drawString(name + ", puedes seleccionar tu juego presionando el botón", 100, 305);
        gr.drawString("del color correspondiente en cada punta de Stella", 100, 325);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal3(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton blue;
    private javax.swing.JButton cyan;
    private javax.swing.JButton green;
    private javax.swing.JButton magenta;
    private javax.swing.JPanel panel;
    private javax.swing.JButton red;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables

}
